const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Fitness AI Backend API',
    description: 'API Documentation for the Fitness AI project. Automatically generated by swagger-autogen.',
  },
  host: 'localhost:5000',
  schemes: ['http', 'https'],
};

const outputFile = './swagger_output.json';
const endpointsFiles = ['./server.js'];

/* NOTE: if you use the express Router, you must pass in the 
   'endpointsFiles' only the root file where the route starts. */
swaggerAutogen(outputFile, endpointsFiles).then(() => {
    console.log("Swagger documentation generated successfully.");
});
